server:
  port: 30001
spring:
  application:
    name: eureka01
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xiaohuan?characterEncoding=utf-8&serverTimezone=GMT%2B8
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000

eureka:
  client:
    allow-redirects: true
    register-with-eureka: false #服务注册,是否将自己注册到服务中
    fetch-registry: false #服务发现,是否从eureka中获取注册信息
    service-url:
      defaultZone: http://localhost:30001/eureka/
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 6000 #服务注册表清理间隔(单位毫秒默认60*1000)
    my-url: http://localhost:30001/eureka/
    response-cache-update-interval-ms: 3000